### ISSUE TITLE
txqueuelen incompatible on Android systems

### ISSUE THREAD

**Issue by FalsNameMcAlias** [cryptostorm/conflinux#1]
This configuration file, due to the fact that there is no android-specific conf I could find, seems to be meant for those systems as well. However, the "txqueuelen 686" line in the configuration provides an error, due to the fact that it is not implemented in Android, or at least the OpenVPN app recommended to be used with cstorm.

**Comment by jlgoz** [comment]
You should be using an Android configuration file not the Linux config file.

**Comment by df-cryptostorm** [comment]
Woops. This repo should be deleted, it's pretty old. 
https://github.com/cryptostorm/cryptostorm_client_configuration_files is where configs are going from now on (also reachable at https://github.com/cryptostorm/conf and https://github.com/cryptostorm/config)
